name: '[5.0] Build & Test'

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.301

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build tests/ABCo.ABSave.UnitTests/ABCo.ABSave.UnitTests.csproj --no-restore --framework net5.0 --configuration Release
      
      - name: Run Tests
        run: dotnet test --no-build --configuration Release