name: Build & Test .NET Standard 2.0

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build ABSave
        run: dotnet build --no-restore --framework netcoreapp2.0 --configuration Release
      
      - name: Run Tests
        run: dotnet test --no-build --configuration Release