name: Build & Test .NET Standard 2.1

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.301

      - name: Restore Packages
        run: dotnet restore

      - name: Build ABSave
        run: dotnet build ABCo.ABSave/ABCo.ABSave.csproj --no-restore --framework netstandard2.0 --configuration Release 
        run: dotnet build tests/ABCo.ABSave.UnitTests/ABCo.ABSave.UnitTests.csproj --no-restore --configuration Release
      
      - name: Run Tests
        run: dotnet test --no-build --configuration Release