name: '[Standard 2.0] Build & Test'

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.0.x'

      - name: Build & Restore
        run: dotnet build tests/ABCo.ABSave.UnitTests/ABCo.ABSave.UnitTests.csproj --configuration Release --framework netcoreapp2.1 
      
      - name: Test
        run: dotnet test --no-build --configuration Release --framework netcoreapp2.1